# Generated by Django 2.0.4 on 2018-04-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('unique_post_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('zip_code', models.CharField(max_length=5)),
                ('available_from', models.DateField()),
                ('accomodates', models.IntegerField()),
                ('expected_rent', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('posted_by', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
        migrations.AddField(
            model_name='post',
            name='citites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.City'),
        ),
        migrations.AddField(
            model_name='post',
            name='new_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.State'),
        ),
    ]
