# Generated by Django 2.0.4 on 2018-04-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(blank=True, choices=[('Paying Guest', 'Paying Guest'), ('Roommate', 'Roommate'), ('Condo', 'Condo'), ('House', 'House'), ('Apartment', 'Apartment')], max_length=50, null=True)),
                ('title', models.CharField(max_length=500)),
                ('unique_post_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=5)),
                ('available_from', models.DateField()),
                ('accomodates', models.IntegerField()),
                ('expected_rent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('posted_by', models.CharField(max_length=150)),
                ('attached_bath', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=5)),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=10)),
                ('lease_type', models.CharField(choices=[('monthly', 'Monthly'), ('three months', 'Three Months'), ('six months', 'Six Months'), ('nine months', 'Nine Months'), ('one year', 'One Year')], max_length=200)),
                ('amenities', models.CharField(max_length=500)),
                ('smoke_policy', models.CharField(choices=[('yes', 'YES'), ('no', 'NO'), ('outside only', 'OUTSIDE ONLY')], max_length=100)),
                ('veg_non_veg_preference', models.CharField(max_length=200)),
                ('pet_friendly', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=5)),
                ('furnishing_details', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
        migrations.AddField(
            model_name='post',
            name='cities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.City'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.State'),
        ),
    ]
