# Generated by Django 2.0.4 on 2018-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180423_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accomodates',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('more than 5', 'More than 5')], max_length=10),
        ),
    ]
